android.useAndroidX=true
GOOGLE_MAPS_API_KEY=AIzaSyBU8cG2UuNw7i-6m7azb1cUIiNgX0DJ4KA
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
hermesEnabled=true
edgeToEdgeEnabled=false

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g

MYAPP_UPLOAD_STORE_FILE=smartcall-release-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=smartcall-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=Clab@1234
MYAPP_UPLOAD_KEY_PASSWORD=Clab@1234
newArchEnabled=false